<a href="https://colab.research.google.com/github/1998456/1998456/blob/main/QUANTIUM(TASK2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## IMPORT LIBRARIES

In [1]:
import pandas as pd
import numpy as np

In [2]:
df= pd.read_csv("/content/QVI_data.csv")

In [3]:
df.head()

,LYLTY_CARD_NBR,DATE,STORE_NBR,TXN_ID,PROD_NBR,PROD_NAME,PROD_QTY,TOT_SALES,PACK_SIZE,BRAND,LIFESTAGE,PREMIUM_CUSTOMER
0,1000,2018-10-17,1,1,5,Natural Chip Compny SeaSalt175g,2,6.0,175,NATURAL,YOUNG SINGLES/COUPLES,Premium
1,1002,2018-09-16,1,2,58,Red Rock Deli Chikn&Garlic Aioli 150g,1,2.7,150,RRD,YOUNG SINGLES/COUPLES,Mainstream
2,1003,2019-03-07,1,3,52,Grain Waves Sour Cream&Chives 210G,1,3.6,210,GRNWVES,YOUNG FAMILIES,Budget
3,1003,2019-03-08,1,4,106,Natural ChipCo Hony Soy Chckn175g,1,3.0,175,NATURAL,YOUNG FAMILIES,Budget
4,1004,2018-11-02,1,5,96,WW Original Stacked Chips 160g,1,1.9,160,WOOLWORTHS,OLDER SINGLES/COUPLES,Mainstream

## TOTAL SALES

In [4]:
tot_sales= sum(df["TOT_SALES"])

In [5]:
print(tot_sales)

351935.45000000304

There's no customer column in the dataset but it could be retrieved from TX_ID because it's unique for every individual

In [6]:
df.describe()

,LYLTY_CARD_NBR,STORE_NBR,TXN_ID,PROD_NBR,PROD_QTY,TOT_SALES,PACK_SIZE
count,48855.000000,48855.000000,48855.000000,48855.000000,48855.000000,48855.000000,48855.000000
mean,27745.755276,27.576420,24956.094975,56.461693,1.873299,7.203673,182.628472
std,15726.046046,15.727747,14398.727749,32.840060,0.377872,2.592786,64.521303
min,1000.000000,1.000000,1.000000,1.000000,1.000000,1.500000,70.000000
25%,13219.000000,13.000000,12479.500000,28.000000,2.000000,5.400000,150.000000
50%,28073.000000,28.000000,24966.000000,55.000000,2.000000,7.400000,170.000000
75%,40291.000000,40.000000,37434.500000,85.000000,2.000000,8.800000,175.000000
max,55232.000000,55.000000,49891.000000,114.000000,5.000000,29.500000,380.000000

## TOTAL CUSTOMER

In [7]:
Total_customer= 49891

## Total Number Of Transaction per Customer

In [8]:
df.shape

(48855, 12)

In [10]:
avg_trns= Total_customer/48855

In [ ]:
print(avg_trns)