<a href="https://colab.research.google.com/github/1998456/1998456/blob/main/R_PROGRAMMING(6).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# EQUALITY

In [4]:
# Relational Database;
# Using Equality & Inequality command for Evaluaton;
4 == (7+2)

TRUE == FALSE

'blake' != 'r'

5 == (3+2)

[1] FALSE

[1] FALSE

[1] TRUE

[1] TRUE

In [5]:
-5*10 == 52-102

'USER' == 'Users'

FALSE != 0

[1] TRUE

[1] FALSE

[1] FALSE

In [8]:
# Greater & Less than;
(3+2)>5

# Determined by Alphabetical order flow;
'dog'<'cats'

# Uses Logical order 0,1;
TRUE <= FALSE

'raining' <= 'raining dogs'

[1] FALSE

[1] FALSE

[1] FALSE

[1] TRUE

# Comparing Vectors

In [9]:
# Linkedin & Facebook Profile views vectors in a week;
linkedin <- c(16,9,13,5,2,17,14)
facebook <- c(17,7,5,16,8,13,14)

In [10]:
# which days did the number of linkedin profiles exceed 15;
linkedin > 15

[1]  TRUE FALSE FALSE FALSE FALSE  TRUE FALSE

In [11]:
# when was your linkedin profile viewed 5times or less;
linkedin <= 5

[1] FALSE FALSE FALSE  TRUE  TRUE FALSE FALSE

In [12]:
# When was your linkedin profile visited more often than your facebook profile;
linkedin > facebook

[1] FALSE  TRUE  TRUE FALSE FALSE  TRUE FALSE

# Comparing Matrices

In [14]:
views= matrix(c(linkedin,facebook) , nrow= 2, byrow= TRUE)
views

     [,1] [,2] [,3] [,4] [,5] [,6] [,7]
[1,] 16   9    13    5   2    17   14
[2,] 17   7     5   16   8    13   14

In [15]:
# When are the views less than 14
views <= 14

     [,1]  [,2] [,3] [,4]  [,5] [,6]  [,7]
[1,] FALSE TRUE TRUE  TRUE TRUE FALSE TRUE
[2,] FALSE TRUE TRUE FALSE TRUE  TRUE TRUE

# AND , OR , NOT ORPERATORS;